import type {
  CommunityPost,
  ExpertProfile,
  PostReply,
  SuccessStory,
  TrendingTopic,
} from '@/types/community';

export const TRENDING_TOPICS: TrendingTopic[] = [
  { id: 't1', tag: 'maize', label: '#MaizePrice 🔥', postCount: 42 },
  { id: 't2', tag: 'tomato-blight', label: '#TomatoBlight ⚠️', postCount: 28 },
  { id: 't3', tag: 'ecocash', label: '#EcocashPayment', postCount: 19 },
  { id: 't4', tag: 'harvest', label: '#HarvestSeason2025', postCount: 35 },
  { id: 't5', tag: 'irrigation', label: '#DripIrrigation', postCount: 15 },
];

export const SUCCESS_STORIES: SuccessStory[] = [
  {
    id: 'ss1',
    name: 'Rudo Chiwara',
    crop: 'Tomatoes',
    earningsUSD: 4200,
    province: 'Marondera',
    quote: 'Sold 8 tonnes to Harare buyers using ZimFarm market prices.',
  },
  {
    id: 'ss2',
    name: 'Tendai Moyo',
    crop: 'Maize',
    earningsUSD: 6800,
    province: 'Bindura',
    quote: 'Used crop planner and got 4.2 tonnes/ha on sandy loam.',
  },
  {
    id: 'ss3',
    name: 'Chipo Makoni',
    crop: 'Honey',
    earningsUSD: 2100,
    province: 'Mutare',
    quote: 'Connected with 3 buyers through the marketplace.',
  },
];

export const EXPERTS: ExpertProfile[] = [
  {
    id: 'e1',
    name: 'Dr. Sarah Mhende',
    title: 'Agronomist',
    organization: 'Agritex Mashonaland East',
    specialties: ['Maize', 'Vegetables', 'Soil fertility'],
    province: 'Marondera',
    available: true,
  },
  {
    id: 'e2',
    name: 'Mr. James Nkomo',
    title: 'Extension Officer',
    organization: 'Agritex Midlands',
    specialties: ['Small grains', 'Irrigation', 'Pests'],
    province: 'Gweru',
    available: true,
  },
  {
    id: 'e3',
    name: 'Dr. Faith Dube',
    title: 'Plant Pathologist',
    organization: 'Cotton Research Institute',
    specialties: ['Tobacco', 'Cotton', 'Disease control'],
    province: 'Kadoma',
    available: false,
  },
];

const daysAgo = (d: number) => {
  const date = new Date();
  date.setDate(date.getDate() - d);
  return date.toISOString();
};

export const MOCK_POSTS: CommunityPost[] = [
  {
    id: 'p1',
    authorId: 'u1',
    authorName: 'Tendai M.',
    authorRole: 'farmer',
    province: 'Harare',
    title: 'Best fertilizer for maize in sandy soil?',
    body: 'I have 2 hectares in Norton with sandy soil. Should I use Compound D only or add AN topdress? What rate per hectare?',
    category: 'question',
    tags: ['maize', 'fertilizer', 'harare'],
    likes: 24,
    commentCount: 8,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: true,
    createdAt: daysAgo(1),
  },
  {
    id: 'p2',
    authorId: 'agritex',
    authorName: 'Agritex Weekly',
    authorRole: 'expert',
    province: 'National',
    title: '📌 Weekly Tips: Prepare for dry spell in Matabeleland',
    body: 'Reduce planting density for dryland maize. Mulch around vegetable seedlings. Check stored grain moisture weekly.',
    category: 'tip',
    tags: ['weather', 'drought', 'agritex'],
    likes: 89,
    commentCount: 12,
    isPinned: true,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(0),
  },
  {
    id: 'p3',
    authorId: 'u2',
    authorName: 'Grace N.',
    authorRole: 'farmer',
    province: 'Bulawayo',
    title: 'Tomato late blight spreading fast — help!',
    body: 'Brown spots on leaves after heavy rains in Bulawayo. Already lost 20% of crop. What fungicide works best?',
    category: 'question',
    tags: ['tomatoes', 'disease', 'tomato-blight'],
    likes: 31,
    commentCount: 15,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(2),
  },
  {
    id: 'p4',
    authorId: 'u3',
    authorName: 'Farai K.',
    authorRole: 'buyer',
    province: 'Harare',
    title: 'Looking for bulk tomatoes — Mbare delivery',
    body: 'Need 500kg grade A tomatoes weekly from May. Pay EcoCash or USD. Reliable farmers please contact.',
    category: 'market',
    tags: ['tomatoes', 'harare', 'buyers'],
    likes: 18,
    commentCount: 22,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(3),
  },
  {
    id: 'p5',
    authorId: 'u4',
    authorName: 'Anonymous Farmer',
    authorRole: 'farmer',
    province: 'Masvingo',
    title: 'How much are you selling maize per kg?',
    body: 'Buyers offering $0.22 at Triangle. Is this fair for this season?',
    category: 'market',
    tags: ['maize', 'maizeprice', 'masvingo'],
    likes: 45,
    commentCount: 34,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: true,
    isSolved: false,
    createdAt: daysAgo(1),
  },
  {
    id: 'p6',
    authorId: 'u5',
    authorName: 'Peter D.',
    authorRole: 'farmer',
    province: 'Chinhoyi',
    title: 'Tip: Use drip irrigation on a budget',
    body: 'Built DIY drip from IV tubing and 200L drums. Cut water use by 40% on my onion plot.',
    category: 'tip',
    tags: ['irrigation', 'onions', 'water'],
    likes: 67,
    commentCount: 9,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(4),
  },
  {
    id: 'p7',
    authorId: 'u6',
    authorName: 'Memory S.',
    authorRole: 'farmer',
    province: 'Gwanda',
    title: 'Fall armyworm on late-planted maize',
    body: 'Worm damage in whorl stage. Sprayed cypermethrin but still seeing damage. Alternative treatments?',
    category: 'question',
    tags: ['maize', 'pests', 'armyworm'],
    likes: 28,
    commentCount: 11,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(5),
  },
  {
    id: 'p8',
    authorId: 'u7',
    authorName: 'Rudo C.',
    authorRole: 'farmer',
    province: 'Marondera',
    title: 'Success: 4 tonnes tomatoes from 0.5 hectares! 🎉',
    body: 'Used ZimFarm planner and sold at $0.85/kg. Total revenue over $3,400 this season.',
    category: 'success',
    tags: ['tomatoes', 'success', 'harvest'],
    likes: 112,
    commentCount: 28,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(6),
  },
  {
    id: 'p9',
    authorId: 'u8',
    authorName: 'Blessing T.',
    authorRole: 'farmer',
    province: 'Mutare',
    title: 'Rain forecast reliable for Manicaland?',
    body: 'Planning to transplant cabbage next week. Weather app says 60% rain — should I wait?',
    category: 'weather',
    tags: ['weather', 'cabbage', 'manicaland'],
    likes: 15,
    commentCount: 7,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(2),
  },
  {
    id: 'p10',
    authorId: 'u9',
    authorName: 'John M.',
    authorRole: 'farmer',
    province: 'Gweru',
    title: 'Hire tractor for 5 hectares — fair price?',
    body: 'Quoted $45/ha for discing in Gweru. Is this reasonable for 2025?',
    category: 'question',
    tags: ['equipment', 'tractor', 'midlands'],
    likes: 19,
    commentCount: 14,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: true,
    createdAt: daysAgo(7),
  },
  {
    id: 'p11',
    authorId: 'u10',
    authorName: 'Chipo M.',
    authorRole: 'buyer',
    province: 'Harare',
    title: 'EcoCash payment delays from buyers — advice?',
    body: 'Sold 200kg beans but buyer says EcoCash failed. How do you protect yourself?',
    category: 'market',
    tags: ['ecocash', 'payment', 'beans'],
    likes: 38,
    commentCount: 19,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(3),
  },
  {
    id: 'p12',
    authorId: 'e1',
    authorName: 'Dr. Sarah Mhende',
    authorRole: 'expert',
    province: 'Marondera',
    title: '✅ Expert: Maize topdress timing',
    body: 'Apply AN when maize is knee-high (V6-V8). Split application on sandy soils: half at knee-high, half 3 weeks later.',
    category: 'tip',
    tags: ['maize', 'fertilizer', 'expert'],
    likes: 56,
    commentCount: 4,
    isPinned: false,
    isExpertAnswer: true,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(4),
  },
  {
    id: 'p13',
    authorId: 'u11',
    authorName: 'David G.',
    authorRole: 'farmer',
    province: 'Bindura',
    title: 'Groundnut aflatoxin prevention tips?',
    body: 'Last season lost crop to mould. How to dry and store properly before selling?',
    category: 'question',
    tags: ['groundnuts', 'storage', 'harvest'],
    likes: 22,
    commentCount: 6,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(8),
  },
  {
    id: 'p14',
    authorId: 'u12',
    authorName: 'Patience G.',
    authorRole: 'farmer',
    province: 'Masvingo',
    title: 'Best time to sell tobacco this year?',
    body: 'Heard prices firming in Harare. Hold or sell now from Masvingo?',
    category: 'market',
    tags: ['tobacco', 'prices', 'masvingo'],
    likes: 27,
    commentCount: 13,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(5),
  },
  {
    id: 'p15',
    authorId: 'u13',
    authorName: 'Simbarashe N.',
    authorRole: 'farmer',
    province: 'Rusape',
    title: 'Intercropping maize and beans — experiences?',
    body: 'Trying maize + sugar beans on 1ha. Any spacing recommendations for Manicaland?',
    category: 'question',
    tags: ['maize', 'beans', 'intercrop'],
    likes: 33,
    commentCount: 17,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(9),
  },
  {
    id: 'p16',
    authorId: 'u14',
    authorName: 'Tinashe M.',
    authorRole: 'both',
    province: 'Harare',
    title: 'Mbare Musika prices this week — tomatoes up 15%',
    body: 'Sharing market report: tomatoes $0.80-0.95/kg, onions $0.55/kg, cabbage $0.35/head.',
    category: 'market',
    tags: ['harare', 'prices', 'tomatoes'],
    likes: 41,
    commentCount: 8,
    isPinned: false,
    isExpertAnswer: false,
    isAnonymous: false,
    isSolved: false,
    createdAt: daysAgo(1),
  },
];

export const MOCK_REPLIES: PostReply[] = [
  {
    id: 'r1',
    postId: 'p1',
    authorId: 'e1',
    authorName: 'Dr. Sarah Mhende',
    authorRole: 'expert',
    body: 'Use 350-400kg Compound D at planting, then 150-200kg AN at knee-high on sandy soils.',
    likes: 18,
    isExpert: true,
    createdAt: daysAgo(0),
    upvotes: 15,
    downvotes: 0,
  },
  {
    id: 'r2',
    postId: 'p1',
    authorId: 'u15',
    authorName: 'Farmer Joe',
    authorRole: 'farmer',
    body: 'I also add cattle manure before ploughing — helps water retention.',
    likes: 5,
    isExpert: false,
    createdAt: daysAgo(0),
    upvotes: 5,
    downvotes: 1,
  },
  {
    id: 'r3',
    postId: 'p3',
    authorId: 'e3',
    authorName: 'Dr. Faith Dube',
    authorRole: 'expert',
    body: 'Apply copper-based fungicide early morning. Improve airflow and avoid overhead irrigation.',
    likes: 22,
    isExpert: true,
    createdAt: daysAgo(1),
    upvotes: 20,
    downvotes: 0,
  },
  {
    id: 'r4',
    postId: 'p3',
    authorId: 'u16',
    authorName: 'Linda P.',
    authorRole: 'farmer',
    body: 'Remove infected leaves immediately and burn them away from field.',
    likes: 8,
    isExpert: false,
    createdAt: daysAgo(1),
    upvotes: 7,
    downvotes: 0,
  },
];

export function timeAgo(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  return `${days}d ago`;
}
