import type { Tutorial } from '@/types/tutorials';

export const TUTORIALS: Tutorial[] = [
  {
    id: 't1',
    title: 'How to grow tomatoes in Zimbabwe: Complete guide',
    category: 'planting',
    emoji: '🍅',
    durationMin: 12,
    difficulty: 'beginner',
    language: 'en',
    featured: true,
    summary: 'From seedbed to harvest — varieties, spacing, and market timing for Zimbabwe.',
    sections: [
      { heading: 'Choosing varieties', body: 'Roma and Star 9009 perform well in most provinces. In hot dry areas, use heat-tolerant types.' },
      { tip: 'Start seedlings 6 weeks before transplanting.', body: 'Use sterilized seed trays and well-drained potting mix.' },
      { heading: 'Field preparation', body: 'Plant at 60cm between rows and 45cm within row. Stake indeterminate varieties.' },
    ],
    relatedIds: ['t2', 't5', 't6'],
  },
  {
    id: 't2',
    title: 'Crop rotation for Zimbabwean smallholder farmers',
    category: 'planting',
    emoji: '🌾',
    durationMin: 8,
    difficulty: 'beginner',
    language: 'en',
    summary: 'Break pest cycles and improve soil fertility with simple rotation plans.',
    sections: [
      { body: 'Follow maize with legumes (beans, cowpeas) to fix nitrogen. Avoid planting tomatoes after potatoes (same disease family).' },
      { tip: 'Keep a 3-year field diary.', body: 'Record what was planted each season to avoid repeating mistakes.' },
    ],
    relatedIds: ['t1', 't8'],
  },
  {
    id: 't3',
    title: 'Dealing with Fall Armyworm on Maize',
    category: 'pest',
    emoji: '🐛',
    durationMin: 10,
    difficulty: 'intermediate',
    language: 'en',
    summary: 'Identify, monitor, and control FAW using integrated pest management.',
    sections: [
      { body: 'Check whorl leaves weekly during vegetative stage. Look for frass and windowing damage.' },
      { heading: 'Control options', body: 'Use recommended insecticides per Agritex bulletin. Apply early morning or evening. Combine with hand-picking on small plots.' },
    ],
    relatedIds: ['t10', 't2'],
  },
  {
    id: 't4',
    title: 'Drip irrigation setup on a budget',
    category: 'watering',
    emoji: '💧',
    durationMin: 15,
    difficulty: 'intermediate',
    language: 'en',
    summary: 'DIY drip systems using drums, filters, and mainline tubing.',
    sections: [
      { body: 'Elevate a 200L drum 1.5m for gravity pressure. Use a simple screen filter before the mainline.' },
      { tip: 'Flush lines weekly.', body: 'Prevents clogging from sediment and algae.' },
    ],
    relatedIds: ['t9', 't1'],
  },
  {
    id: 't5',
    title: 'Post-harvest handling of vegetables',
    category: 'storage',
    emoji: '🥬',
    durationMin: 9,
    difficulty: 'beginner',
    language: 'en',
    summary: 'Reduce losses with proper curing, sorting, and cool storage.',
    sections: [
      { body: 'Harvest early morning. Shade immediately. Sort by grade before packing.' },
      { heading: 'Tomatoes & leafy greens', body: 'Tomatoes: cure 2 days. Leafy greens: mist lightly and sell same day when possible.' },
    ],
    relatedIds: ['t6', 't1'],
  },
  {
    id: 't6',
    title: 'Getting the best price at Mbare Musika',
    category: 'marketing',
    emoji: '🏪',
    durationMin: 7,
    difficulty: 'beginner',
    language: 'en',
    summary: 'Timing, grading, and buyer relationships at Harare\'s main market.',
    sections: [
      { body: 'Arrive Tuesday–Thursday for best wholesale traffic. Grade A produce separately — buyers pay premium for uniform lots.' },
      { tip: 'Build relationships with 2–3 regular buyers.', body: 'Reduces price volatility and post-harvest waste.' },
    ],
    relatedIds: ['t1', 't5'],
  },
  {
    id: 't7',
    title: 'Understanding compound fertilizers: D, S, L grades',
    category: 'planting',
    emoji: '🧪',
    durationMin: 11,
    difficulty: 'intermediate',
    language: 'en',
    summary: 'When to use Compound D, S, and L for maize, tobacco, and vegetables.',
    sections: [
      { body: 'Compound D (basal): high P for root development at planting. Topdress with AN or Urea at knee-high for maize.' },
      { heading: 'Compound L', body: 'Used for legumes and some horticultural crops — check Agritex recommendation for your soil test.' },
    ],
    relatedIds: ['t2', 't8'],
  },
  {
    id: 't8',
    title: 'Water harvesting techniques for dry season',
    category: 'watering',
    emoji: '🌧️',
    durationMin: 10,
    difficulty: 'intermediate',
    language: 'sn',
    summary: 'Contour ridges, tanks, and in-field storage for Matabeleland and dry areas.',
    sections: [
      { body: 'Dig contour ridges on slopes to slow runoff. Connect to small earth dams or tanks where possible.' },
      { tip: 'Even 5,000L storage helps.', body: 'Enough for critical irrigation during flowering.' },
    ],
    relatedIds: ['t4', 't9'],
  },
  {
    id: 't9',
    title: 'Introduction to beekeeping in Zimbabwe',
    category: 'harvest',
    emoji: '🍯',
    durationMin: 14,
    difficulty: 'beginner',
    language: 'en',
    summary: 'Start with top-bar or Langstroth hives — site selection and honey flow.',
    sections: [
      { body: 'Place hives near water and flowering trees, away from footpaths. Register with local beekeepers association.' },
      { heading: 'Harvest', body: 'Harvest when 70% of frames are capped. Filter and bottle in food-grade containers.' },
    ],
    relatedIds: ['t5', 't6'],
  },
  {
    id: 't10',
    title: 'Organic pest control using local plants',
    category: 'pest',
    emoji: '🌿',
    durationMin: 8,
    difficulty: 'advanced',
    language: 'nd',
    summary: 'Neem, chilli, and garlic sprays for smallholder vegetable plots.',
    sections: [
      { body: 'Soak crushed neem leaves overnight. Strain and spray on affected foliage. Reapply after rain.' },
      { tip: 'Test on a few plants first.', body: 'Avoid spraying open flowers to protect pollinators.' },
    ],
    relatedIds: ['t3', 't1'],
  },
  {
    id: 't11',
    title: 'Maize planting depth and population',
    category: 'planting',
    emoji: '🌽',
    durationMin: 6,
    difficulty: 'beginner',
    language: 'en',
    summary: 'Optimal spacing for yield under rainfed and irrigated conditions.',
    sections: [{ body: 'Plant 5cm deep when soil moisture is adequate. Target 37,000–45,000 plants/ha depending on variety and rainfall zone.' }],
    relatedIds: ['t2', 't3'],
  },
  {
    id: 't12',
    title: 'Onion production in sandy soils',
    category: 'planting',
    emoji: '🧅',
    durationMin: 9,
    difficulty: 'intermediate',
    language: 'en',
    summary: 'Transplanting, bulbing stage irrigation, and curing.',
    sections: [{ body: 'Transplant 8-week seedlings. Reduce water as tops fall. Cure 2 weeks in ventilated shade before storage.' }],
    relatedIds: ['t1', 't5'],
  },
  {
    id: 't13',
    title: 'Groundnut harvesting and aflatoxin prevention',
    category: 'harvest',
    emoji: '🥜',
    durationMin: 7,
    difficulty: 'intermediate',
    language: 'en',
    summary: 'Right moisture at digging and drying on raised racks.',
    sections: [{ body: 'Dig when leaves yellow. Dry pods to 8% moisture on raised mesh racks — never on bare soil.' }],
    relatedIds: ['t5'],
  },
  {
    id: 't14',
    title: 'Tobacco seedbed management',
    category: 'planting',
    emoji: '🍃',
    durationMin: 12,
    difficulty: 'advanced',
    language: 'en',
    summary: 'Float tray systems and disease-free seedlings for smallholders.',
    sections: [{ body: 'Use float trays with clean water. Harden seedlings before transplanting to field beds.' }],
    relatedIds: ['t7'],
  },
  {
    id: 't15',
    title: 'Selling via EcoCash and USD — pricing tips',
    category: 'marketing',
    emoji: '💳',
    durationMin: 5,
    difficulty: 'beginner',
    language: 'en',
    summary: 'Dual pricing, confirmation screenshots, and buyer trust.',
    sections: [{ body: 'Quote both USD and ZWG using daily rate. Confirm EcoCash before releasing goods. Keep SMS receipts.' }],
    relatedIds: ['t6'],
  },
  {
    id: 't16',
    title: 'Cabbage transplanting and head formation',
    category: 'planting',
    emoji: '🥬',
    durationMin: 8,
    difficulty: 'beginner',
    language: 'sn',
    summary: 'Cool season planting windows in highveld regions.',
    sections: [{ body: 'Transplant at 4–5 true leaves. Consistent moisture during head formation prevents splitting.' }],
    relatedIds: ['t1', 't5'],
  },
  {
    id: 't17',
    title: 'Cattle dip and tick control calendar',
    category: 'pest',
    emoji: '🐄',
    durationMin: 6,
    difficulty: 'intermediate',
    language: 'en',
    summary: 'Weekly dipping in summer rains — Eastern Highlands schedule.',
    sections: [{ body: 'Follow DAFF/Agritex dip calendar. Alternate actives to prevent resistance.' }],
    relatedIds: ['t10'],
  },
  {
    id: 't18',
    title: 'Solar pump sizing for 1 hectare',
    category: 'watering',
    emoji: '☀️',
    durationMin: 13,
    difficulty: 'advanced',
    language: 'en',
    summary: 'Match pump flow to drip system requirements and storage.',
    sections: [{ body: 'Calculate daily water need (crop ET × area). Size panel array for 4–5 peak sun hours in Zimbabwe.' }],
    relatedIds: ['t4', 't8'],
  },
  {
    id: 't19',
    title: 'Bean intercropping with maize',
    category: 'planting',
    emoji: '🫘',
    durationMin: 7,
    difficulty: 'beginner',
    language: 'nd',
    summary: 'Spatial arrangement for nitrogen fixation without shade stress.',
    sections: [{ body: 'Plant beans between maize rows 2 weeks after maize emergence. Choose short-season bean varieties.' }],
    relatedIds: ['t2', 't11'],
  },
  {
    id: 't20',
    title: 'Cold storage without electricity',
    category: 'storage',
    emoji: '❄️',
    durationMin: 9,
    difficulty: 'intermediate',
    language: 'en',
    summary: 'Charcoal cooler (zeer pot) and shade structures for vegetables.',
    sections: [{ body: 'Double-pot charcoal coolers can extend shelf life 2–3 days for leafy greens in hot weather.' }],
    relatedIds: ['t5', 't6'],
  },
];

export const DAILY_TIPS = [
  'Mulch around tomato seedlings to conserve moisture in sandy soils.',
  'Check maize whorls weekly during rainy season for fall armyworm.',
  'Grade produce before going to market — uniform lots earn 10–15% more.',
  'Apply basal fertilizer in a band, not broadcast, for better efficiency.',
  'Harvest honey only when 70% of comb cells are capped.',
  'Rotate legumes after maize to restore soil nitrogen naturally.',
];

export function getDailyTip(): string {
  const day = Math.floor(Date.now() / 86400000);
  return DAILY_TIPS[day % DAILY_TIPS.length];
}

export function getFeaturedTutorial(): Tutorial {
  return TUTORIALS.find((t) => t.featured) ?? TUTORIALS[0];
}
