import type { Crop } from '@/types';

import { crop } from './crop-helpers';

export const CROPS: Crop[] = [
  crop({ id: 'tomatoes', name: 'Tomatoes', localName: 'Madomasi', category: 'vegetable', currentPriceUSD: 0.85, currentPriceZWG: 85, priceChangePercent: 5.2, demandLevel: 'very_high', bestPlantingMonths: [3, 4, 8, 9], harvestDays: 75, waterRequirements: 'medium', soilType: ['Loam', 'Sandy-Loam'], description: 'High-value horticultural crop year-round in irrigated systems.', tips: 'Stake plants and mulch to reduce blight.' }),
  crop({ id: 'maize', name: 'Maize', localName: 'Chibage', category: 'grain', currentPriceUSD: 0.28, currentPriceZWG: 28, priceChangePercent: -2.1, demandLevel: 'very_high', bestPlantingMonths: [11, 12, 1], harvestDays: 120, waterRequirements: 'medium', soilType: ['Loam', 'Clay-Loam'], description: 'Staple grain crop; main rainy season planting.', tips: 'Plant with first effective rains; scout for Fall Armyworm.' }),
  crop({ id: 'tobacco', name: 'Tobacco', localName: 'Fodya', category: 'cash crop', currentPriceUSD: 3.2, currentPriceZWG: 320, priceChangePercent: 1.8, demandLevel: 'high', bestPlantingMonths: [9, 10], harvestDays: 150, waterRequirements: 'medium', soilType: ['Sandy-Loam', 'Loam'], description: 'Major export cash crop in Mashonaland.', tips: 'Follow contracted buyer grading standards.' }),
  crop({ id: 'cotton', name: 'Cotton', localName: 'Dzungu', category: 'cash crop', currentPriceUSD: 0.45, currentPriceZWG: 45, priceChangePercent: 3.0, demandLevel: 'medium', bestPlantingMonths: [11, 12], harvestDays: 160, waterRequirements: 'medium', soilType: ['Clay-Loam', 'Loam'], description: 'Grown in low rainfall areas with supplemental irrigation.', tips: 'Integrated pest management for bollworm.' }),
  crop({ id: 'sugarcane', name: 'Sugarcane', localName: 'Shuga', category: 'cash crop', currentPriceUSD: 0.12, currentPriceZWG: 12, priceChangePercent: 0.5, demandLevel: 'high', bestPlantingMonths: [10, 11], harvestDays: 365, waterRequirements: 'high', soilType: ['Loam', 'Clay'], description: 'Long-term ratoon crop in Lowveld.', tips: 'Requires reliable water and mill contract.' }),
  crop({ id: 'soyabeans', name: 'Soyabeans', localName: 'Soya', category: 'legume', currentPriceUSD: 0.52, currentPriceZWG: 52, priceChangePercent: 4.1, demandLevel: 'high', bestPlantingMonths: [11, 12], harvestDays: 110, waterRequirements: 'medium', soilType: ['Loam'], description: 'Oilseed and livestock feed crop.', tips: 'Inoculate seed for nitrogen fixation.' }),
  crop({ id: 'groundnuts', name: 'Groundnuts', localName: 'Nzungu / Nyimo', category: 'legume', currentPriceUSD: 0.95, currentPriceZWG: 95, priceChangePercent: 2.3, demandLevel: 'high', bestPlantingMonths: [11, 12, 1], harvestDays: 120, waterRequirements: 'low', soilType: ['Sandy', 'Sandy-Loam'], description: 'Drought-tolerant legume for smallholders.', tips: 'Harvest when leaves yellow to avoid aflatoxin.' }),
  crop({ id: 'sweet-potatoes', name: 'Sweet Potatoes', localName: 'Mbambaira', category: 'vegetable', currentPriceUSD: 0.35, currentPriceZWG: 35, priceChangePercent: 1.2, demandLevel: 'high', bestPlantingMonths: [10, 11, 3], harvestDays: 120, waterRequirements: 'low', soilType: ['Sandy', 'Sandy-Loam'], description: 'Nutritious root crop with good storage.', tips: 'Use vine cuttings from disease-free stock.' }),
  crop({ id: 'potatoes', name: 'Potatoes', localName: 'Mbambaira chena', category: 'vegetable', currentPriceUSD: 0.55, currentPriceZWG: 55, priceChangePercent: 6.0, demandLevel: 'very_high', bestPlantingMonths: [3, 4, 8], harvestDays: 90, waterRequirements: 'medium', soilType: ['Loam', 'Sandy-Loam'], description: 'Cool-season crop in highveld.', tips: 'Rotate to reduce bacterial wilt.' }),
  crop({ id: 'onions', name: 'Onions', localName: 'Hanyanisi', category: 'vegetable', currentPriceUSD: 0.65, currentPriceZWG: 65, priceChangePercent: 4.5, demandLevel: 'very_high', bestPlantingMonths: [3, 4, 5], harvestDays: 100, waterRequirements: 'medium', soilType: ['Loam'], description: 'Popular market vegetable with strong urban demand.', tips: 'Cure bulbs before storage.' }),
  crop({ id: 'cabbage', name: 'Cabbage', localName: 'Kabichi', category: 'vegetable', currentPriceUSD: 0.4, currentPriceZWG: 40, priceChangePercent: 2.0, demandLevel: 'high', bestPlantingMonths: [3, 4, 8, 9], harvestDays: 80, waterRequirements: 'medium', soilType: ['Loam'], description: 'Cool-season brassica for fresh markets.', tips: 'Control diamondback moth early.' }),
  crop({ id: 'spinach', name: 'Spinach', localName: 'Muriwo wemuriwo', category: 'vegetable', currentPriceUSD: 0.5, currentPriceZWG: 50, priceChangePercent: 3.2, demandLevel: 'high', bestPlantingMonths: [3, 4, 5, 8], harvestDays: 45, waterRequirements: 'medium', soilType: ['Loam', 'Sandy-Loam'], description: 'Quick-turn leafy green for urban markets.', tips: 'Succession plant every 3 weeks.' }),
  crop({ id: 'peppers', name: 'Peppers', localName: 'Piripiri / Pepa', category: 'vegetable', currentPriceUSD: 1.2, currentPriceZWG: 120, priceChangePercent: 7.0, demandLevel: 'very_high', bestPlantingMonths: [8, 9, 3], harvestDays: 90, waterRequirements: 'medium', soilType: ['Loam'], description: 'Sweet and hot varieties for fresh and dried markets.', tips: 'Avoid overhead irrigation late in season.' }),
  crop({ id: 'cucumbers', name: 'Cucumbers', localName: 'Cucumber', category: 'vegetable', currentPriceUSD: 0.7, currentPriceZWG: 70, priceChangePercent: 2.8, demandLevel: 'high', bestPlantingMonths: [9, 10, 3], harvestDays: 60, waterRequirements: 'high', soilType: ['Loam'], description: 'Greenhouse and open-field production.', tips: 'Harvest frequently to maintain yield.' }),
  crop({ id: 'carrots', name: 'Carrots', localName: 'Karoti', category: 'vegetable', currentPriceUSD: 0.6, currentPriceZWG: 60, priceChangePercent: 1.5, demandLevel: 'medium', bestPlantingMonths: [3, 4, 8], harvestDays: 85, waterRequirements: 'medium', soilType: ['Sandy-Loam', 'Loam'], description: 'Root crop for salad and processing markets.', tips: 'Fine seedbed needed for uniform roots.' }),
  crop({ id: 'beans', name: 'Beans', localName: 'Nyemba', category: 'legume', currentPriceUSD: 1.1, currentPriceZWG: 110, priceChangePercent: 3.5, demandLevel: 'high', bestPlantingMonths: [11, 12, 3], harvestDays: 70, waterRequirements: 'medium', soilType: ['Loam'], description: 'Common beans for food security and income.', tips: 'Avoid waterlogging.' }),
  crop({ id: 'cowpeas', name: 'Cowpeas', localName: 'Nyemba dzechibage', category: 'legume', currentPriceUSD: 0.75, currentPriceZWG: 75, priceChangePercent: 2.0, demandLevel: 'medium', bestPlantingMonths: [11, 12], harvestDays: 75, waterRequirements: 'low', soilType: ['Sandy', 'Sandy-Loam'], description: 'Heat and drought tolerant legume.', tips: 'Good intercrop with maize.' }),
  crop({ id: 'sorghum', name: 'Sorghum', localName: 'Mabhero', category: 'grain', currentPriceUSD: 0.32, currentPriceZWG: 32, priceChangePercent: 1.0, demandLevel: 'medium', bestPlantingMonths: [11, 12], harvestDays: 110, waterRequirements: 'low', soilType: ['Sandy', 'Sandy-Loam'], description: 'Dryland cereal for arid regions.', tips: 'Bird control at maturity is critical.' }),
  crop({ id: 'millet', name: 'Millet', localName: 'Mhunga', category: 'grain', currentPriceUSD: 0.38, currentPriceZWG: 38, priceChangePercent: 0.8, demandLevel: 'medium', bestPlantingMonths: [11, 12], harvestDays: 100, waterRequirements: 'low', soilType: ['Sandy'], description: 'Traditional small grain in drier areas.', tips: 'Process for meal and brewing markets.' }),
  crop({ id: 'sunflower', name: 'Sunflower', localName: 'Sunflower', category: 'cash crop', currentPriceUSD: 0.48, currentPriceZWG: 48, priceChangePercent: 2.5, demandLevel: 'medium', bestPlantingMonths: [11, 12], harvestDays: 100, waterRequirements: 'low', soilType: ['Loam', 'Sandy-Loam'], description: 'Oilseed crop with growing processor demand.', tips: 'Watch birds and head rot in wet years.' }),
  crop({ id: 'papaya', name: 'Papaya', localName: 'Papaya', category: 'fruit', currentPriceUSD: 0.9, currentPriceZWG: 90, priceChangePercent: 4.0, demandLevel: 'medium', bestPlantingMonths: [10, 11, 3], harvestDays: 270, waterRequirements: 'medium', soilType: ['Loam', 'Sandy-Loam'], description: 'Tropical fruit for fresh consumption.', tips: 'Plant virus-free seedlings.' }),
  crop({ id: 'mangoes', name: 'Mangoes', localName: 'Mango', category: 'fruit', currentPriceUSD: 0.55, currentPriceZWG: 55, priceChangePercent: 5.5, demandLevel: 'high', bestPlantingMonths: [10, 11], harvestDays: 180, waterRequirements: 'low', soilType: ['Sandy-Loam', 'Loam'], description: 'Seasonal fruit with export and local potential.', tips: 'Bag fruit to reduce fruit fly damage.' }),
  crop({ id: 'avocado', name: 'Avocado', localName: 'Avocado', category: 'fruit', currentPriceUSD: 0.8, currentPriceZWG: 80, priceChangePercent: 8.0, demandLevel: 'very_high', bestPlantingMonths: [10, 11], harvestDays: 365, waterRequirements: 'medium', soilType: ['Loam'], description: 'High-value tree crop for export markets.', tips: 'Hass varieties need good drainage.' }),
  crop({ id: 'bananas', name: 'Bananas', localName: 'Makohwa', category: 'fruit', currentPriceUSD: 0.25, currentPriceZWG: 25, priceChangePercent: 1.2, demandLevel: 'high', bestPlantingMonths: [1, 2, 10, 11], harvestDays: 300, waterRequirements: 'high', soilType: ['Loam', 'Clay-Loam'], description: 'Staple fruit in high rainfall areas.', tips: 'Remove suckers to manage plant population.' }),
  crop({ id: 'citrus', name: 'Citrus', localName: 'Madimu', category: 'fruit', currentPriceUSD: 0.45, currentPriceZWG: 45, priceChangePercent: 2.2, demandLevel: 'medium', bestPlantingMonths: [10, 11], harvestDays: 365, waterRequirements: 'medium', soilType: ['Loam', 'Sandy-Loam'], description: 'Oranges, lemons, naartjies for juice and fresh.', tips: 'Monitor for citrus greening in nurseries.' }),
  crop({ id: 'watermelon', name: 'Watermelon', localName: 'Watermelon', category: 'fruit', currentPriceUSD: 0.35, currentPriceZWG: 35, priceChangePercent: 6.5, demandLevel: 'high', bestPlantingMonths: [9, 10, 11], harvestDays: 85, waterRequirements: 'medium', soilType: ['Sandy', 'Sandy-Loam'], description: 'Summer fruit with strong roadside sales.', tips: 'Pollination improves with bees nearby.' }),
  crop({ id: 'butternut', name: 'Butternut', localName: 'Butternut', category: 'vegetable', currentPriceUSD: 0.42, currentPriceZWG: 42, priceChangePercent: 2.0, demandLevel: 'high', bestPlantingMonths: [9, 10, 3], harvestDays: 95, waterRequirements: 'medium', soilType: ['Loam'], description: 'Popular cucurbit with good storage.', tips: 'Cure in shade before marketing.' }),
  crop({ id: 'pumpkin', name: 'Pumpkin', localName: 'Mananga', category: 'vegetable', currentPriceUSD: 0.3, currentPriceZWG: 30, priceChangePercent: 1.0, demandLevel: 'medium', bestPlantingMonths: [11, 12], harvestDays: 100, waterRequirements: 'low', soilType: ['Loam', 'Sandy-Loam'], description: 'Food security crop with long shelf life.', tips: 'Leave stem on fruit when harvesting.' }),
  crop({ id: 'garlic', name: 'Garlic', localName: 'Garlic', category: 'vegetable', currentPriceUSD: 2.5, currentPriceZWG: 250, priceChangePercent: 9.0, demandLevel: 'very_high', bestPlantingMonths: [3, 4], harvestDays: 150, waterRequirements: 'medium', soilType: ['Loam', 'Sandy-Loam'], description: 'High-value bulb crop for niche markets.', tips: 'Plant cloves; avoid waterlogging.' }),
  crop({ id: 'ginger', name: 'Ginger', localName: 'Ginger', category: 'vegetable', currentPriceUSD: 1.8, currentPriceZWG: 180, priceChangePercent: 5.0, demandLevel: 'high', bestPlantingMonths: [10, 11], harvestDays: 240, waterRequirements: 'high', soilType: ['Loam'], description: 'Spice crop for fresh and dried markets.', tips: 'Mulch heavily in hot dry season.' }),
  crop({ id: 'chillies', name: 'Chillies', localName: 'Piripiri', category: 'vegetable', currentPriceUSD: 1.5, currentPriceZWG: 150, priceChangePercent: 4.8, demandLevel: 'high', bestPlantingMonths: [8, 9, 3], harvestDays: 80, waterRequirements: 'medium', soilType: ['Loam'], description: 'Export and local spice markets.', tips: 'Dry on raised racks to preserve color.' }),
  crop({ id: 'mushrooms', name: 'Mushrooms', localName: 'Mushrooms', category: 'vegetable', currentPriceUSD: 4.0, currentPriceZWG: 400, priceChangePercent: 10.0, demandLevel: 'very_high', bestPlantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], harvestDays: 45, waterRequirements: 'high', soilType: ['Loam'], description: 'Indoor oyster and button mushroom production.', tips: 'Sterile substrate prevents contamination.' }),
  crop({ id: 'cassava', name: 'Cassava', localName: 'Mufarinjiwa', category: 'vegetable', currentPriceUSD: 0.22, currentPriceZWG: 22, priceChangePercent: 0.5, demandLevel: 'low', bestPlantingMonths: [10, 11], harvestDays: 300, waterRequirements: 'low', soilType: ['Sandy', 'Sandy-Loam'], description: 'Root crop in warmer lowveld areas.', tips: 'Process to reduce cyanide before consumption.' }),
  crop({ id: 'wheat', name: 'Wheat', localName: 'Wheat', category: 'grain', currentPriceUSD: 0.35, currentPriceZWG: 35, priceChangePercent: -1.0, demandLevel: 'medium', bestPlantingMonths: [5, 6], harvestDays: 130, waterRequirements: 'medium', soilType: ['Clay-Loam', 'Loam'], description: 'Winter cereal in irrigated highveld.', tips: 'Requires frost-free dry harvest period.' }),
  crop({ id: 'barley', name: 'Barley', localName: 'Barley', category: 'grain', currentPriceUSD: 0.33, currentPriceZWG: 33, priceChangePercent: 0.2, demandLevel: 'low', bestPlantingMonths: [5, 6], harvestDays: 125, waterRequirements: 'medium', soilType: ['Loam'], description: 'Malting and feed grain under irrigation.', tips: 'Contract with brewery before planting.' }),
];

export const getTopDemandCrops = (limit = 8): Crop[] =>
  [...CROPS]
    .sort((a, b) => {
      const order = { very_high: 4, high: 3, medium: 2, low: 1 };
      return order[b.demandLevel] - order[a.demandLevel];
    })
    .slice(0, limit);

export const getCropsForMonth = (month: number): Crop[] =>
  CROPS.filter((c) => c.bestPlantingMonths.includes(month));
