import type { MarketProduct } from '@/types';

import { USD_TO_ZWG_RATE } from './provinces-seasons';

function p(partial: Omit<MarketProduct, 'priceZWG'> & { priceZWG?: number }): MarketProduct {
  return { ...partial, priceZWG: partial.priceZWG ?? Math.round(partial.priceUSD * USD_TO_ZWG_RATE) };
}

export const EXTRA_MARKET_PRODUCTS: MarketProduct[] = [
  p({ id: 'seed-cabbage-f1', name: 'Broccoli Seed F1', category: 'Seeds & Seedlings', priceUSD: 18, unit: 'pack', sellerId: 's2', sellerName: 'GreenGrow Seeds', location: 'Marondera', rating: 4.5, reviewCount: 31, inStock: true, images: [], description: 'Heat-tolerant broccoli for highveld.', isOrganic: false, isCertified: true }),
  p({ id: 'seed-pepper-bell', name: 'Bell Pepper Seed Mix', category: 'Seeds & Seedlings', priceUSD: 14, unit: 'pack', sellerId: 's2', sellerName: 'GreenGrow Seeds', location: 'Marondera', rating: 4.4, reviewCount: 44, inStock: true, images: [], description: 'Red, yellow, green pepper mix.', isOrganic: false, isCertified: false }),
  p({ id: 'seed-spinach', name: 'Spinach Seed Bloomsdale', category: 'Seeds & Seedlings', priceUSD: 6, unit: 'pack', sellerId: 's3', sellerName: 'FarmLink Bulawayo', location: 'Bulawayo', rating: 4.3, reviewCount: 28, inStock: true, images: [], description: 'Slow-bolting spinach variety.', isOrganic: true, isCertified: false }),
  p({ id: 'seed-watermelon', name: 'Watermelon Seed Crimson', category: 'Seeds & Seedlings', priceUSD: 22, unit: 'pack', sellerId: 's1', sellerName: 'AgriSupplies Harare', location: 'Harare', rating: 4.6, reviewCount: 52, inStock: true, images: [], description: 'Sweet red flesh watermelon.', isOrganic: false, isCertified: true }),
  p({ id: 'seed-butternut', name: 'Butternut Seed Waltham', category: 'Seeds & Seedlings', priceUSD: 10, unit: 'pack', sellerId: 's4', sellerName: 'Mashonaland Agro', location: 'Bindura', rating: 4.5, reviewCount: 39, inStock: true, images: [], description: 'Popular butternut variety.', isOrganic: false, isCertified: false }),
  p({ id: 'equip-wheelbarrow', name: 'Heavy Duty Wheelbarrow', category: 'Farm Equipment', priceUSD: 55, unit: 'each', sellerId: 'e1', sellerName: 'ToolMaster ZW', location: 'Harare', rating: 4.4, reviewCount: 88, inStock: true, images: [], description: '65L steel tray wheelbarrow.', isOrganic: false, isCertified: false }),
  p({ id: 'equip-greenhouse', name: 'Greenhouse Tunnel 8x30m', category: 'Farm Equipment', priceUSD: 1200, unit: 'kit', sellerId: 'e2', sellerName: 'IrriTech Zimbabwe', location: 'Mutare', rating: 4.6, reviewCount: 12, inStock: true, images: [], description: 'Mid-size greenhouse tunnel kit.', isOrganic: false, isCertified: true }),
  p({ id: 'equip-scale', name: 'Digital Platform Scale 300kg', category: 'Farm Equipment', priceUSD: 180, unit: 'each', sellerId: 'e1', sellerName: 'ToolMaster ZW', location: 'Harare', rating: 4.7, reviewCount: 34, inStock: true, images: [], description: 'Battery-powered farm scale.', isOrganic: false, isCertified: true }),
  p({ id: 'equip-planter', name: 'Maize Seed Planter (2-row)', category: 'Farm Equipment', priceUSD: 320, unit: 'each', sellerId: 'e3', sellerName: 'Mashonaland Mechanisation', location: 'Chinhoyi', rating: 4.2, reviewCount: 19, inStock: true, images: [], description: 'Manual/Jersey bull planter.', isOrganic: false, isCertified: false }),
  p({ id: 'equip-ox-plow', name: 'Ox-Drawn Moldboard Plow', category: 'Farm Equipment', priceUSD: 95, unit: 'each', sellerId: 'e3', sellerName: 'Mashonaland Mechanisation', location: 'Chinhoyi', rating: 4.1, reviewCount: 41, inStock: true, images: [], description: 'Traditional animal-drawn plow.', isOrganic: false, isCertified: false }),
  p({ id: 'chem-glyphosate', name: 'Glyphosate 360 1L', category: 'Agrochemicals', priceUSD: 12, unit: 'bottle', sellerId: 'c2', sellerName: 'AgroChem Bulawayo', location: 'Bulawayo', rating: 4.0, reviewCount: 167, inStock: true, images: [], description: 'Non-selective herbicide.', isOrganic: false, isCertified: false }),
  p({ id: 'chem-compound-l', name: 'Compound L (50kg)', category: 'Agrochemicals', priceUSD: 29, unit: 'bag', sellerId: 'c1', sellerName: 'ChemCrop Ltd', location: 'Harare', rating: 4.5, reviewCount: 134, inStock: true, images: [], description: 'For legumes and vegetables.', isOrganic: false, isCertified: true }),
  p({ id: 'chem-lime', name: 'Agricultural Lime (50kg)', category: 'Agrochemicals', priceUSD: 8, unit: 'bag', sellerId: 'c1', sellerName: 'ChemCrop Ltd', location: 'Harare', rating: 4.3, reviewCount: 98, inStock: true, images: [], description: 'Correct soil acidity.', isOrganic: false, isCertified: false }),
  p({ id: 'honey-creamed', name: 'Creamed Honey 500g', category: 'Honey & Bee Products', priceUSD: 8, unit: 'jar', sellerId: 'h1', sellerName: 'Mazowe Valley Honey', location: 'Mazowe', rating: 4.8, reviewCount: 36, inStock: true, images: [], description: 'Smooth spreadable creamed honey.', isOrganic: true, isCertified: false }),
  p({ id: 'honey-chilli', name: 'Chilli Infused Honey 250g', category: 'Honey & Bee Products', priceUSD: 7, unit: 'jar', sellerId: 'h2', sellerName: 'BeeNatural ZW', location: 'Mutare', rating: 4.7, reviewCount: 24, inStock: true, images: [], description: 'Zimbabwe bird eye chilli honey.', isOrganic: true, isCertified: false }),
  p({ id: 'honey-royal', name: 'Royal Jelly 10g', category: 'Honey & Bee Products', priceUSD: 25, unit: 'vial', sellerId: 'h1', sellerName: 'Mazowe Valley Honey', location: 'Mazowe', rating: 4.6, reviewCount: 11, inStock: true, images: [], description: 'Fresh royal jelly supplement.', isOrganic: true, isCertified: false }),
  p({ id: 'honey-pollen', name: 'Bee Pollen Granules 200g', category: 'Honey & Bee Products', priceUSD: 15, unit: 'jar', sellerId: 'h2', sellerName: 'BeeNatural ZW', location: 'Mutare', rating: 4.5, reviewCount: 17, inStock: true, images: [], description: 'Dried bee pollen.', isOrganic: true, isCertified: false }),
  p({ id: 'honey-2kg', name: 'Raw Honey 2kg Bucket', category: 'Honey & Bee Products', priceUSD: 20, unit: 'bucket', sellerId: 'h1', sellerName: 'Mazowe Valley Honey', location: 'Mazowe', rating: 4.9, reviewCount: 48, inStock: true, images: [], description: 'Bulk raw honey for resellers.', isOrganic: true, isCertified: false }),
  p({ id: 'animal-chicken', name: 'Whole Chicken (2kg)', category: 'Animal Products', priceUSD: 7, unit: 'each', sellerId: 'a1', sellerName: 'Sunrise Poultry Farm', location: 'Harare', rating: 4.6, reviewCount: 112, inStock: true, images: [], description: 'Fresh broiler chicken.', isOrganic: false, isCertified: false }),
  p({ id: 'animal-cheese', name: 'Farmhouse Cheese 500g', category: 'Animal Products', priceUSD: 6, unit: 'block', sellerId: 'a2', sellerName: 'DairyDale Midlands', location: 'Gweru', rating: 4.5, reviewCount: 43, inStock: true, images: [], description: 'Mild cheddar-style cheese.', isOrganic: false, isCertified: true }),
  p({ id: 'animal-butter', name: 'Farm Butter 250g', category: 'Animal Products', priceUSD: 4, unit: 'pack', sellerId: 'a2', sellerName: 'DairyDale Midlands', location: 'Gweru', rating: 4.4, reviewCount: 58, inStock: true, images: [], description: 'Salted farm butter.', isOrganic: false, isCertified: false }),
  p({ id: 'produce-cabbage', name: 'Fresh Cabbage (10 heads)', category: 'Harvested Crops', priceUSD: 6, unit: 'bundle', sellerId: 'f1', sellerName: 'Mbare Fresh Farms', location: 'Harare', rating: 4.3, reviewCount: 72, inStock: true, images: [], description: 'Grade 1 fresh cabbage.', isOrganic: false, isCertified: false }),
  p({ id: 'produce-spinach', name: 'Spinach Bunches (20)', category: 'Harvested Crops', priceUSD: 5, unit: 'bundle', sellerId: 'f1', sellerName: 'Mbare Fresh Farms', location: 'Harare', rating: 4.4, reviewCount: 91, inStock: true, images: [], description: 'Daily-picked spinach bunches.', isOrganic: true, isCertified: false }),
  p({ id: 'produce-peppers', name: 'Mixed Peppers (8kg)', category: 'Harvested Crops', priceUSD: 12, unit: 'crate', sellerId: 'f2', sellerName: 'Chipinge Growers', location: 'Manicaland', rating: 4.5, reviewCount: 63, inStock: true, images: [], description: 'Sweet bell peppers mixed colors.', isOrganic: false, isCertified: false }),
  p({ id: 'produce-avocado', name: 'Hass Avocados (kg)', category: 'Harvested Crops', priceUSD: 1.2, unit: 'kg', sellerId: 'f2', sellerName: 'Chipinge Growers', location: 'Manicaland', rating: 4.7, reviewCount: 88, inStock: true, images: [], description: 'Export-grade Hass avocados.', isOrganic: false, isCertified: true }),
  p({ id: 'pack-jute', name: 'Jute Produce Bags (50)', category: 'Packaging & Storage', priceUSD: 35, unit: 'pack', sellerId: 'p1', sellerName: 'PackRight ZW', location: 'Harare', rating: 4.2, reviewCount: 27, inStock: true, images: [], description: '50kg jute storage bags.', isOrganic: false, isCertified: false }),
  p({ id: 'pack-cold-box', name: 'Polystyrene Cold Box', category: 'Packaging & Storage', priceUSD: 18, unit: 'each', sellerId: 'p1', sellerName: 'PackRight ZW', location: 'Harare', rating: 4.1, reviewCount: 19, inStock: true, images: [], description: 'For fresh produce transport.', isOrganic: false, isCertified: false }),
  p({ id: 'produce-green-mealies', name: 'Green Mealies (20)', category: 'Harvested Crops', priceUSD: 4, unit: 'bundle', sellerId: 'f3', sellerName: 'GrainCo Mash West', location: 'Chinhoyi', rating: 4.0, reviewCount: 54, inStock: false, images: [], description: 'Fresh green maize cobs.', isOrganic: false, isCertified: false }),
  p({ id: 'chem-fungicide', name: 'Mancozeb 80WP 1kg', category: 'Agrochemicals', priceUSD: 15, unit: 'pack', sellerId: 'c2', sellerName: 'AgroChem Bulawayo', location: 'Bulawayo', rating: 4.4, reviewCount: 76, inStock: true, images: [], description: 'Broad-spectrum fungicide.', isOrganic: false, isCertified: true }),
];
